version: '3.5'

services:
  ohif_viewer:
    build:
      context: ./../../../../
      dockerfile: ./platform/app/.recipes/OpenResty-Orthanc-Keycloak/Dockerfile
    image: ohif_viewer:latest
    container_name: ohif_viewer
    volumes:
      - ./config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./config/ssl:/usr/local/openresty/nginx/conf/ssl:ro
      - ./logs/nginx:/var/logs/nginx
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - keycloak
      - orthanc
    restart: on-failure

  orthanc:
    image: jodogne/orthanc-plugins
    hostname: orthanc
    container_name: orthanc
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    # environment:
    #   - ORTHANC__REMOTEACCESSALLOWED=true
    #   - ORTHANC__HTTPPORT=8042
    # ports:
    #   - '8042:8042'
    #   - '4242:4242'
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:6.0.0
    hostname: keycloak
    container_name: keycloak
    volumes:
      - ./volumes/keycloak-themes/ohif:/opt/jboss/keycloak/themes/ohif
      - ./config/ohif-keycloak-realm.json:/tmp/ohif-keycloak-realm.json
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/ohif-keycloak-realm.json
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - postgres
    ports:
      - '8080:8080'
      - '8443:8443'
    restart: unless-stopped

  postgres:
    image: postgres:11.2
    hostname: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    # ports:
    #   - '5432:5432'
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
